In [1]:
import torch

In [3]:
sp_scores = torch.load("/home/sbaruah_usc_edu/mica_text_coref/data/movie_coref/results/coreference/epoch_1/john_wick_10.sp_scores.pt")
starts = torch.load("/home/sbaruah_usc_edu/mica_text_coref/data/movie_coref/results/coreference/epoch_1/john_wick_10.starts.pt")
ends = torch.load("/home/sbaruah_usc_edu/mica_text_coref/data/movie_coref/results/coreference/epoch_1/john_wick_10.ends.pt")

In [4]:
sp_scores.shape, starts.shape, ends.shape

(torch.Size([130, 2005, 2]), torch.Size([130]), torch.Size([130]))

In [5]:
starts

tensor([1383,  323,  933,   61,  479,  245,  190, 1378, 1599,  153,  208, 1406,
         291,   75,  459, 1751,  186, 1980, 1393, 1168,   11,  218,  145, 1398,
        1127,   35,  806, 1811, 1622,  150, 1564, 1605,  618, 1968,  403,  169,
        1592,  949, 1867,  926,  348,  389, 1092, 1165,  523,  876,  321,  771,
         725, 1482, 1129, 1900,  661, 1859,  303, 1992,   46,    0, 1463, 1469,
         887, 1075, 1566, 1887,   40, 1294, 1296,  653, 1296, 1282, 1273, 1048,
        1971, 1907, 1329, 1347, 1214, 1522, 1352, 1931, 1192,  490, 1945, 1344,
        1055, 1982, 1202, 1052, 2001, 1913, 1909,  481, 1919, 1244, 1543, 1713,
        1337, 1355, 1878,  929,  180, 1105,  175,  947, 1112,  243,  226,  702,
         540,  645,  831,  865,  965,  466,  847,  637,  476,  629,  663, 1226,
         448,  707,  844,  509,  222,  657,  536,  469,  841,  568],
       device='cuda:0')

In [7]:
ind = torch.arange(len(sp_scores), device="cuda:0")

In [8]:
sp_scores[ind, starts]

tensor([[ 24.8867,  22.1794],
        [ 27.8450,  26.9249],
        [ 28.1075,  20.9796],
        [ 19.4671,  20.4199],
        [ 15.4153,  20.3948],
        [ 15.4339,  11.7717],
        [ 28.5561,  23.7061],
        [  1.7500,  22.9963],
        [ 17.2454,  15.5889],
        [ 11.9622,  18.8099],
        [ 21.0580,  24.7004],
        [ 24.6615,  20.4308],
        [ 16.1664,  18.6737],
        [  8.2579,  12.7850],
        [ 22.4862, -14.4654],
        [ -3.3253,   9.5335],
        [ 16.0863,  14.9659],
        [ 20.1875,  15.2769],
        [ 24.9868,  21.8145],
        [ 19.9373,  20.1461],
        [ 17.5671,  28.8992],
        [ 13.0795,  10.2789],
        [ 25.7975,  27.1882],
        [ 18.0610,  15.3687],
        [ 15.0953,  11.3149],
        [ 11.1086,  21.4234],
        [  6.0943,   6.1035],
        [  8.8732,  19.1831],
        [ 13.8265,  18.5338],
        [ 26.0431,  24.5120],
        [  9.4878,   2.1091],
        [ 17.3099,  15.8772],
        [ 11.6751,  15.2245],
        [ 

In [9]:
sp_scores[ind, ends]

tensor([[ 24.8867,  22.1794],
        [ 27.8450,  26.9249],
        [ 28.1075,  20.9796],
        [ 19.4671,  20.4199],
        [ 15.4153,  20.3948],
        [ 15.4339,  11.7717],
        [ 28.5561,  23.7061],
        [  1.7500,  22.9963],
        [ 17.2454,  15.5889],
        [ 11.9622,  18.8099],
        [ 21.0580,  24.7004],
        [ 24.6615,  20.4308],
        [ 16.1664,  18.6737],
        [  8.2579,  12.7850],
        [-33.5043,   6.8153],
        [ -3.3253,   9.5335],
        [ 16.0863,  14.9659],
        [ 20.1875,  15.2769],
        [ 24.9868,  21.8145],
        [ 19.9373,  20.1461],
        [ 17.5671,  28.8992],
        [ 13.0795,  10.2789],
        [ 25.7975,  27.1882],
        [ 18.0610,  15.3687],
        [ 15.0953,  11.3149],
        [ 11.1086,  21.4234],
        [  6.0943,   6.1035],
        [  8.8732,  19.1831],
        [ 13.8265,  18.5338],
        [ 26.0431,  24.5120],
        [  9.4878,   2.1091],
        [ 17.3099,  15.8772],
        [ 11.6751,  15.2245],
        [ 