In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

In [2]:
X = torch.randn(2, 5, 3)
m = (torch.randn(2, 5) > 0).float()
print(X)
print(m)

tensor([[[-1.0752, -0.3575,  0.7541],
         [ 1.0310,  0.0269,  0.3751],
         [ 0.6719,  0.2817, -0.1625],
         [ 0.2165,  0.6278, -0.3881],
         [-1.0943, -0.6758,  0.6926]],

        [[-0.5461,  0.6498, -1.9800],
         [-2.6015,  0.3352,  0.2845],
         [-1.8133,  0.0763,  1.5321],
         [ 0.4707, -0.1743,  0.0800],
         [ 0.9736,  1.9798,  0.3037]]])
tensor([[0., 1., 0., 1., 1.],
        [1., 0., 0., 1., 0.]])


In [3]:
X[m == 1]

tensor([[ 1.0310,  0.0269,  0.3751],
        [ 0.2165,  0.6278, -0.3881],
        [-1.0943, -0.6758,  0.6926],
        [-0.5461,  0.6498, -1.9800],
        [ 0.4707, -0.1743,  0.0800]])

In [4]:
y = torch.randint(0, 5, (2, 4, 2))
y

tensor([[[0, 4],
         [0, 1],
         [1, 1],
         [3, 2]],

        [[0, 2],
         [3, 0],
         [0, 4],
         [4, 3]]])

In [5]:
z = y[~((y[:,:,0] == 0) & (y[:,:,1] == 0))]
z

tensor([[0, 4],
        [0, 1],
        [1, 1],
        [3, 2],
        [0, 2],
        [3, 0],
        [0, 4],
        [4, 3]])

In [6]:
z - z[0, 0]

tensor([[0, 4],
        [0, 1],
        [1, 1],
        [3, 2],
        [0, 2],
        [3, 0],
        [0, 4],
        [4, 3]])

In [7]:
class B(nn.Module):

    def __init__(self) -> None:
        super().__init__()
        self.scorer = nn.Linear(5, 5)

class A(nn.Module):

    def __init__(self) -> None:
        super().__init__()
        self.embedding = nn.Embedding(100, 5)
        self.b = B()

In [8]:
a = A()

In [9]:
for name, param in a.state_dict().items():
    print(name, param.shape)
print()
for name, param in a.b.state_dict().items():
    print(name, param.shape)
print()
for name, param in a.b.scorer.state_dict().items():
    print(name, param.shape)

embedding.weight torch.Size([100, 5])
b.scorer.weight torch.Size([5, 5])
b.scorer.bias torch.Size([5])

scorer.weight torch.Size([5, 5])
scorer.bias torch.Size([5])

weight torch.Size([5, 5])
bias torch.Size([5])


In [10]:
weights = torch.load(
    "/home/sbaruah_usc_edu/mica_text_coref/data/word_level_coref/"
    "roberta_(e20_2021.05.02_01.16)_release.pt")

In [11]:
weights.keys()

dict_keys(['bert', 'we', 'rough_scorer', 'pw', 'a_scorer', 'sp', 'epochs_trained'])

In [12]:
{**weights["rough_scorer"], **weights["we"]}

{'bilinear.weight': tensor([[ 1.7543e-01, -2.7519e-02,  1.4653e-02,  ..., -1.0604e-02,
           2.5374e-02, -1.7066e-03],
         [ 4.9204e-02,  1.3426e-01, -9.1869e-03,  ..., -4.4060e-03,
           8.7263e-03, -9.5577e-03],
         [-1.7296e-02, -1.0086e-02,  5.9279e-02,  ...,  1.6338e-05,
          -3.0986e-02, -2.6442e-02],
         ...,
         [-8.4727e-04, -7.4070e-02, -3.5817e-02,  ...,  1.2996e-01,
          -6.5809e-02, -1.6725e-02],
         [-2.8037e-02,  2.8999e-03,  3.8483e-02,  ..., -9.9639e-03,
           1.5081e-01, -3.2012e-02],
         [ 7.8245e-03,  2.4031e-02, -1.3260e-03,  ...,  1.7210e-02,
           2.2953e-02,  7.6747e-02]], device='cuda:0'),
 'bilinear.bias': tensor([ 0.0298, -0.0126, -0.0024,  ..., -0.0076, -0.0152, -0.0162],
        device='cuda:0'),
 'attn.weight': tensor([[-0.0294,  0.0403, -0.0034,  ..., -0.0082, -0.0159, -0.0712]],
        device='cuda:0'),
 'attn.bias': tensor([-0.0024], device='cuda:0')}

In [13]:
a = torch.randn(16, 5, 2)
b = torch.randn(16, 10, 3)
dataset = TensorDataset(a, b)
dataloader = DataLoader(dataset, batch_size=4)

In [4]:
w = torch.randn(8, 10)
z = torch.zeros(2, 10)
x = torch.cat([w, z], dim=0)

In [18]:
m = torch.all(x == 0, dim=2)

In [19]:
y = torch.randn(10, 10)
y[m]

tensor([-1.7250, -0.0444, -0.5992,  0.2924,  0.3578,  0.3092, -1.1077,  1.5696,
        -0.7574,  0.5782,  0.4106,  0.7527, -1.3133,  0.7745, -0.1598,  1.0465,
        -1.4606, -3.2379, -0.8222, -0.6616])

In [20]:
def f(a, b, c):
    print(locals())

f(2, 3, 4)

{'a': 2, 'b': 3, 'c': 4}


: 

In [5]:
x

tensor([[ 0.9250,  0.3608, -3.0117,  0.1590, -0.0606,  2.3719,  0.9134, -0.0360,
         -0.5744,  0.2070],
        [ 1.0417,  1.2063,  0.3591,  0.2993, -0.3557, -0.7325,  0.0092, -0.4611,
          1.0492, -0.4233],
        [-0.3487, -1.9598, -1.3769,  0.1079,  1.1457,  0.4545,  0.2155, -0.5677,
         -1.0215,  0.4028],
        [-1.3148,  0.5996,  0.1653,  0.0870, -1.1551, -0.6461,  0.6678, -1.7923,
          0.4132, -0.2877],
        [ 1.0405, -0.4415,  0.5741, -0.4718,  0.2769, -1.5073,  0.6070, -0.1545,
         -0.2004, -1.3671],
        [ 1.3014, -1.3853, -0.0137, -1.2518, -0.1628,  1.3376,  2.1291, -0.4357,
         -0.4761,  0.9772],
        [-1.5233, -0.0439,  0.1956,  0.5214,  1.2178, -0.4873, -0.7024, -0.1746,
         -2.5409, -0.8621],
        [ 2.3561, -0.5601,  2.0302,  0.9249,  0.5761,  0.0125,  0.1271,  0.1514,
          0.7440,  0.2006],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000,  

In [8]:
x[~(x == 0).all(dim=1)]

tensor([[ 0.9250,  0.3608, -3.0117,  0.1590, -0.0606,  2.3719,  0.9134, -0.0360,
         -0.5744,  0.2070],
        [ 1.0417,  1.2063,  0.3591,  0.2993, -0.3557, -0.7325,  0.0092, -0.4611,
          1.0492, -0.4233],
        [-0.3487, -1.9598, -1.3769,  0.1079,  1.1457,  0.4545,  0.2155, -0.5677,
         -1.0215,  0.4028],
        [-1.3148,  0.5996,  0.1653,  0.0870, -1.1551, -0.6461,  0.6678, -1.7923,
          0.4132, -0.2877],
        [ 1.0405, -0.4415,  0.5741, -0.4718,  0.2769, -1.5073,  0.6070, -0.1545,
         -0.2004, -1.3671],
        [ 1.3014, -1.3853, -0.0137, -1.2518, -0.1628,  1.3376,  2.1291, -0.4357,
         -0.4761,  0.9772],
        [-1.5233, -0.0439,  0.1956,  0.5214,  1.2178, -0.4873, -0.7024, -0.1746,
         -2.5409, -0.8621],
        [ 2.3561, -0.5601,  2.0302,  0.9249,  0.5761,  0.0125,  0.1271,  0.1514,
          0.7440,  0.2006]])

: 