In [1]:
import jsonlines
import os
import torch

In [2]:
def read_data(file: str) -> list[dict[str, any]]:
    data = []
    for record in jsonlines.open(file):
        data.append(record)
    return data

test_data = read_data(os.path.join(os.getenv("DATA_DIR"), "mica_text_coref/word_level_coref/data/english_test.jsonlines"))
test_head_data = read_data(os.path.join(os.getenv("DATA_DIR"), "mica_text_coref/word_level_coref/data/english_test_head.jsonlines"))
wl_data = read_data(os.path.join(os.getenv("DATA_DIR"), "mica_text_coref/movie_coref/results/nocharacters/dev_wl.jsonlines"))

In [3]:
print("Test data keys:")
print(sorted(test_data[0].keys()))
print()
print("Test head data keys:")
print(sorted(test_head_data[0].keys()))
print()
print("Movie wl data keys:")
print(sorted(wl_data[0].keys()))

Test data keys:
['cased_words', 'clusters', 'deprel', 'document_id', 'head', 'part_id', 'pos', 'sent_id', 'speaker']

Test head data keys:
['cased_words', 'deprel', 'document_id', 'head', 'head2span', 'part_id', 'pos', 'sent_id', 'span_clusters', 'speaker', 'word_clusters']

Movie wl data keys:
['cased_words', 'clusters', 'document_id', 'movie', 'ner', 'parse', 'pos', 'rater', 'sent_id', 'sent_offset', 'speaker', 'token']


In [4]:
x = torch.randn((5, 10, 2))
begin = torch.randint(0, 10, (5,))
end = torch.randint(0, 10, (5,))
print(x)
print(begin)
print(end)

tensor([[[ 0.0053, -1.1427],
         [ 1.1517, -0.5650],
         [-0.2592,  0.0463],
         [-0.7502, -0.3397],
         [ 1.3639, -0.6883],
         [ 0.5855, -1.4111],
         [-0.1561, -0.0643],
         [-0.3551, -0.0843],
         [ 0.3785, -0.0939],
         [ 1.4607,  0.0503]],

        [[-1.0029,  0.6369],
         [-0.7867,  1.9302],
         [-0.7180,  0.9436],
         [ 1.0888,  0.7847],
         [-0.1953, -1.1461],
         [ 2.3971,  1.5287],
         [ 0.8477, -1.3446],
         [ 0.8969, -0.2355],
         [ 1.4858, -2.1018],
         [ 0.5305,  0.7799]],

        [[-0.4550, -1.1771],
         [-0.4935,  0.6656],
         [-1.0973, -0.1597],
         [-0.3182,  0.0915],
         [-1.2603,  0.5439],
         [-0.2815, -0.6508],
         [ 1.0573, -0.1857],
         [ 0.5304,  0.3747],
         [ 0.9656, -0.9544],
         [-0.4946,  0.6317]],

        [[ 1.1656, -0.8925],
         [ 1.2404,  0.5655],
         [-0.3637, -1.0791],
         [-0.0625, -0.6238],
        

In [8]:
begin_mask = x[torch.arange(5), begin, 0] > 0
end_mask = x[torch.arange(5), end, 1] > 0
mask = begin_mask & end_mask
print(begin_mask)
print(end_mask)
print(mask)

tensor([ True,  True, False, False,  True])
tensor([ True,  True, False,  True,  True])
tensor([ True,  True, False, False,  True])


In [9]:
x[mask]

tensor([[[ 0.0053, -1.1427],
         [ 1.1517, -0.5650],
         [-0.2592,  0.0463],
         [-0.7502, -0.3397],
         [ 1.3639, -0.6883],
         [ 0.5855, -1.4111],
         [-0.1561, -0.0643],
         [-0.3551, -0.0843],
         [ 0.3785, -0.0939],
         [ 1.4607,  0.0503]],

        [[-1.0029,  0.6369],
         [-0.7867,  1.9302],
         [-0.7180,  0.9436],
         [ 1.0888,  0.7847],
         [-0.1953, -1.1461],
         [ 2.3971,  1.5287],
         [ 0.8477, -1.3446],
         [ 0.8969, -0.2355],
         [ 1.4858, -2.1018],
         [ 0.5305,  0.7799]],

        [[ 3.0125, -0.8138],
         [ 0.3376, -0.5527],
         [-0.4518, -0.7942],
         [-1.0849,  0.7477],
         [-1.3466, -0.2871],
         [ 1.8179,  0.3310],
         [ 0.9555,  0.7195],
         [ 1.3161, -0.8686],
         [-0.1097,  1.0350],
         [ 0.2546, -1.2728]]])

In [10]:
weights = torch.load(os.path.join(os.getenv("DATA_DIR"), "mica_text_coref/word_level_coref/roberta_(e20_2021.05.02_01.16)_release.pt"))

In [11]:
weights.keys()

dict_keys(['bert', 'we', 'rough_scorer', 'pw', 'a_scorer', 'sp', 'epochs_trained'])

In [12]:
weights["epochs_trained"]

20