In [1]:
import torch

In [2]:
n = 100

In [3]:
m = 25

In [5]:
head_ids = torch.randint(0, n, (m,))

In [6]:
head_ids

tensor([58, 96, 51, 41, 58,  4, 32, 44, 86, 66,  8,  5, 57, 27, 83, 68, 85, 28,
        75, 70, 93, 32, 35, 43, 81])

In [7]:
relative_positions = head_ids.unsqueeze(1) - torch.arange(0, n).unsqueeze(0)

In [8]:
relative_positions

tensor([[ 58,  57,  56,  ..., -39, -40, -41],
        [ 96,  95,  94,  ...,  -1,  -2,  -3],
        [ 51,  50,  49,  ..., -46, -47, -48],
        ...,
        [ 35,  34,  33,  ..., -62, -63, -64],
        [ 43,  42,  41,  ..., -54, -55, -56],
        [ 81,  80,  79,  ..., -16, -17, -18]])

In [9]:
l = 10
r = 5

In [13]:
valid_positions = (-r <= relative_positions) & (relative_positions <= l)

In [16]:
valid_positions.nonzero(as_tuple=True)

(tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
          2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,
          3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
          4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,
          6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,
          7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,
          8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,
          9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12,
         12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13,
         13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14,
         14, 14, 14, 14, 14,

: 